include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    avoid_unnecessary_containers: true

    always_put_control_body_on_new_line: true
    always_specify_types: false
    avoid_print: true
    avoid_empty_else: true
    unnecessary_this: true

    sort_child_properties_last: true
    prefer_final_fields: true
    prefer_final_locals: true
    directives_ordering: true
    library_prefixes: true
    prefer_single_quotes: true

    use_key_in_widget_constructors: true
    avoid_classes_with_only_static_members: true
    avoid_positional_boolean_parameters: true
    public_member_api_docs: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
  errors:
    invalid_annotation_target: ignore
